Update MaxHeapAdhoc.js
trekhleb/javascript-algorithms pull request #1460
Opened 2024-11-01 17:16 UTC by aniruddhaadak80

### Improvements Made:

1. **Context Handling**: Fixed the issue with the `forEach` method by using an arrow function to preserve the context of `this`.

2. **Performance Optimization in `poll()`**: Simplified the logic to replace the top element with the last element and directly called `heapifyDown()` only if the heap is not empty after removing the top.

3. **Cleaner `heapifyDown()` Logic**: Streamlined the logic for determining the larger child index. This makes it clearer and avoids unnecessary comparisons.

4. **Destructuring in `swap()`**: Used array destructuring for swapping elements, which is more concise and readable.

5. **Optional Return Value in `peek()`**: Updated the `peek()` method to return `undefined` if the heap is empty, enhancing clarity.

### Overall, these changes improve the maintainability, readability, and performance of the code while retaining the core functionality of the max heap data structure.

2024-11-01 17:18 UTC, lazarljubenovic commented
Stahp

2024-11-13 05:17 UTC, anandfresh requested changes

2024-11-13 05:17 UTC, anandfresh commented on src/data-structures/heap/MaxHeapAdhoc.js
> +      this.heapifyDown(); // Re-establish the heap property
Why do we explicitly check? `!this.isEmpty()` here at line no 27 as we are returning undefined if `this.isEmpty()` is true.
So the lines 25 to 29 will execute only if `!this.isEmpty()` is true.  This check is redundant here.

2026-01-05 21:48 UTC, lisagorewitdecker commented
> 
> 
> ### Improvements Made:
> 
> 
> 
> 1. **Context Handling**: Fixed the issue with the `forEach` method by using an arrow function to preserve the context of `this`.
> 
> 
> 
> 2. **Performance Optimization in `poll()`**: Simplified the logic to replace the top element with the last element and directly called `heapifyDown()` only if the heap is not empty after removing the top.
> 
> 
> 
> 3. **Cleaner `heapifyDown()` Logic**: Streamlined the logic for determining the larger child index. This makes it clearer and avoids unnecessary comparisons.
> 
> 
> 
> 4. **Destructuring in `swap()`**: Used array destructuring for swapping elements, which is more concise and readable.
> 
> 
> 
> 5. **Optional Return Value in `peek()`**: Updated the `peek()` method to return `undefined` if the heap is empty, enhancing clarity.
> 
> 
> 
> ### Overall, these changes improve the maintainability, readability, and performance of the code while retaining the core functionality of the max heap data structure.

2026-01-05 21:49 UTC, lisagorewitdecker approved these changes

2026-08-25 07:05 UTC, aniruddhaadak80 commented
Withdrawing this pull request. It was AI-generated boilerplate and does not meet the contribution bar for this repository. Apologies for the noise.

2026-08-25 07:05 UTC, closed without merging