Improved docsUpdate README.md
trekhleb/javascript-algorithms pull request #553
Opened 2020-10-01 11:01 UTC by ManasSingh-dev

2020-10-01 13:04 UTC, leandrocodes requested changes

2020-10-01 13:04 UTC, leandrocodes commented on README.md
> +# JavaScript Algorithms and Data Structure- The compete guide
```suggestion
# JavaScript Algorithms and Data Structure - The complete guide
```

2020-12-02 21:00 UTC, lazarljubenovic commented
@trekhleb Obvious Hacktober spam. We can close this one.

2020-12-08 17:10 UTC, trekhleb commented
It is better to keep the header concise. No reason to add the `The complete guide` suffix.

2020-12-08 17:10 UTC, closed without merging